### ISSUE TITLE
Swift Programming Language Book

### ISSUE THREAD

**Issue by ghost** [niutech/swiftlang#3]
Hello,

When will you update the PDF version of the Swift Programming Language Book?

**Comment by niutech** [comment]
As soon as I get the PDF version. The iBook version is protected by DRM. If you can convert the iBook, please send it to me.

**Comment by Bertomatic** [comment]
Thanks for your reply niutech! Unfortunately, I didn't manage to find it without DRM. :-(

**Comment by niutech** [comment]
I have updated the [PDF version of the ebook](https://googledrive.com/host/0BzEbtMoF6IXbNXdfQ3REdXBUaVk/The%20Swift%20Programming%20Language%20%28Swift%202.1%29.pdf)
